services:
  - type: web
    name: myntra-scrape-pro
    env: python
    plan: free
    buildCommand: |
      chmod +x render-build.sh
      ./render-build.sh
      pip install -r requirements.txt
    startCommand: streamlit run app.py --server.port 10000 --server.address 0.0.0.0
    envVars:
      - key: MONGO_DB_URL
        sync: true
